version: "3.7"

services:

  nginx:
    build: docker
    command: nginx
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

  php-fpm:
    build: docker
    command: php-fpm
    volumes:
      - .:/var/www:delegated
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini:delegated
